language: python
dist: trusty
sudo: required
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get install -y libtool pkg-config gettext fontconfig libfontconfig1-dev cmake libzip-dev libjpeg-dev
  - git config --global http.sslVerify "false"
  - git clone --branch poppler-0.62.0 --depth 1 https://anongit.freedesktop.org/git/poppler/poppler.git poppler_src 
  - cd poppler_src/
  - cmake -DENABLE_SPLASH=OFF -DENABLE_UTILS=OFF -DENABLE_LIBOPENJPEG=none . 
  - make 
  - cp libpoppler.so.?? ../pdfparser/
  - cp cpp/libpoppler-cpp.so.? ../pdfparser
  - cd ..
  
install:
  - pip install cython
  - POPPLER_ROOT=poppler_src python setup.py build_ext --inplace
# command to run tests
script:
  - cd tests
  - PYTHONPATH=.. python dump_file.py ../test_docs/test1.pdf | grep zasahovat
  